In [1]:
import torch
import numpy

In [3]:
# Создаем тензор
x = torch.rand([3, 4])
x = torch.zeros([3, 4])
x = torch.ones([3, 4])
x = torch.eye(3, 4)

x = torch.Tensor(
[[1,  2,  3,  4],
 [5,  6,  7,  8],
 [9, 10, 11, 12]])

print (x, '<- tensor')
print (x.size(), '<- tensor size')
print (x.size(0), '<- dimension size')
print (x[1:, 1:3], '<- slicing support')


  1   2   3   4
  5   6   7   8
  9  10  11  12
[torch.FloatTensor of size 3x4]
 <- tensor
torch.Size([3, 4]) <- tensor size
3 <- dimension size

  6   7
 10  11
[torch.FloatTensor of size 2x2]
 <- slicing support


In [5]:
# Копирование (по ссылке и глубокое)
y = x

y[1, :] = 1
print (x, y, '<- shallow copy')

y = x.clone()
y[1, :] = 2
print (x, y, '<- deep copy')


  1   2   3   4
  1   1   1   1
  9  10  11  12
[torch.FloatTensor of size 3x4]
 
  1   2   3   4
  1   1   1   1
  9  10  11  12
[torch.FloatTensor of size 3x4]
 <- shallow copy

  1   2   3   4
  1   1   1   1
  9  10  11  12
[torch.FloatTensor of size 3x4]
 
  1   2   3   4
  2   2   2   2
  9  10  11  12
[torch.FloatTensor of size 3x4]
 <- deep copy


In [35]:
# Математические операции (стандартные поэлементные)
print( x + y, x * y, x / y, x - y, x % y, x**2, x**y, '<- basic math')


  2   4   6   8
  3   3   3   3
 18  20  22  24
[torch.FloatTensor of size 3x4]
 
   1    4    9   16
   2    2    2    2
  81  100  121  144
[torch.FloatTensor of size 3x4]
 
 1.0000  1.0000  1.0000  1.0000
 0.5000  0.5000  0.5000  0.5000
 1.0000  1.0000  1.0000  1.0000
[torch.FloatTensor of size 3x4]
 
 0  0  0  0
-1 -1 -1 -1
 0  0  0  0
[torch.FloatTensor of size 3x4]
 
 0  0  0  0
 1  1  1  1
 0  0  0  0
[torch.FloatTensor of size 3x4]
 
   1    4    9   16
   1    1    1    1
  81  100  121  144
[torch.FloatTensor of size 3x4]
 
 1.0000e+00  4.0000e+00  2.7000e+01  2.5600e+02
 1.0000e+00  1.0000e+00  1.0000e+00  1.0000e+00
 3.8742e+08  1.0000e+10  2.8531e+11  8.9161e+12
[torch.FloatTensor of size 3x4]
 <- basic math


In [6]:
x.dot(y.transpose(0,1))

362.0

In [8]:
# Более сложные операции
print (torch.exp(x))
print (torch.log(x))
print (torch.sin(x))


 2.7183e+00  7.3891e+00  2.0086e+01  5.4598e+01
 2.7183e+00  2.7183e+00  2.7183e+00  2.7183e+00
 8.1031e+03  2.2026e+04  5.9874e+04  1.6275e+05
[torch.FloatTensor of size 3x4]


 0.0000  0.6931  1.0986  1.3863
 0.0000  0.0000  0.0000  0.0000
 2.1972  2.3026  2.3979  2.4849
[torch.FloatTensor of size 3x4]


 0.8415  0.9093  0.1411 -0.7568
 0.8415  0.8415  0.8415  0.8415
 0.4121 -0.5440 -1.0000 -0.5366
[torch.FloatTensor of size 3x4]



In [9]:
# Логические операции
y = x[x > 3]
print(y)
y = (x > 3)
print(y)


  4
  9
 10
 11
 12
[torch.FloatTensor of size 5]


 0  0  0  1
 0  0  0  0
 1  1  1  1
[torch.ByteTensor of size 3x4]



In [11]:
# Переопределение типа
x = x.float()
print (x)
x = x.double()
print (x)
x = x.int()
print(x)
x = x.float()


  1   2   3   4
  1   1   1   1
  9  10  11  12
[torch.FloatTensor of size 3x4]


  1   2   3   4
  1   1   1   1
  9  10  11  12
[torch.DoubleTensor of size 3x4]


  1   2   3   4
  1   1   1   1
  9  10  11  12
[torch.IntTensor of size 3x4]



In [12]:
# Взаимодействие с Numpy
x = numpy.array([[1, 2, 3, 4], [4, 3, 2, 1]])
print (x)
x = torch.from_numpy(x)
print (x)
x = x.numpy()
print (x)
x = torch.from_numpy(x).float()

[[1 2 3 4]
 [4 3 2 1]]

 1  2  3  4
 4  3  2  1
[torch.LongTensor of size 2x4]

[[1 2 3 4]
 [4 3 2 1]]


In [13]:
# Перемещение на GPU
import time
x_cuda = x.cuda()
print (x_cuda, '<- CUDA Tensor!')
start = time.time()
y = (x - x + x*10.0) ** 2
print (time.time() - start, '<- CPU time')
start = time.time()
y_cuda = (x_cuda - x_cuda + x_cuda * 10.0) ** 2
print (time.time() - start, '<- GPU time' )
y = y_cuda.cpu()
print (y)
# print(x ** 2, '<- operation performed on the GPU!!!')
# print x = 

AssertionError: 
Found no NVIDIA driver on your system. Please check that you
have an NVIDIA GPU and installed a driver from
http://www.nvidia.com/Download/index.aspx

In [141]:
# Автоматическое (символьное) дифференциирование (обратное распространение градиента) (случай скаляра)
import torch.autograd
x_var = torch.autograd.Variable(x, requires_grad=True)
formula = (torch.exp(x_var) ** 2).sum()
formula.backward()

print x_var.grad, '<- gradient'

Variable containing:
   14.7781   109.1963   806.8576  5961.9155
 5961.9155   806.8576   109.1963    14.7781
[torch.FloatTensor of size 2x4]
 <- gradient
Variable containing:
   14.7781   109.1963   806.8576  5961.9155
 5961.9155   806.8576   109.1963    14.7781
[torch.FloatTensor of size 2x4]
 <- gradient
Variable containing:
    29.5562    218.3926   1613.7152  11923.8311
 11923.8311   1613.7152    218.3926     29.5562
[torch.FloatTensor of size 2x4]
 <- gradient


In [127]:
# Автоматическое дифференциирование (обратное распространение градиента) (случай тензора)
# variable -> formula1 (вектор) -> formula2 (скаляр)
x_var = torch.autograd.Variable(x, requires_grad=True)
formula1 = torch.exp(x_var) ** 2.0
y_var = torch.autograd.Variable(formula1.data.clone(), requires_grad=True)
formula2 = y_var.sum()
formula2.backward()
y_grad = y_var.grad.clone()
print formula1
print y_grad
formula1.backward(gradient=y_grad.data)
print x_var.grad

Variable containing:
    7.3891    54.5982   403.4288  2980.9578
 2980.9578   403.4288    54.5982     7.3891
[torch.FloatTensor of size 2x4]

Variable containing:
 1  1  1  1
 1  1  1  1
[torch.FloatTensor of size 2x4]

Variable containing:
   14.7781   109.1963   806.8576  5961.9155
 5961.9155   806.8576   109.1963    14.7781
[torch.FloatTensor of size 2x4]

